// JavaScript Document
$('#sanpham').owlCarousel({
    loop:true,
    margin:30,
	nav:true,
	autoplay:true,
	smartSpeed:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:3
        }
    }
})
$('#sanpham1').owlCarousel({
    loop:true,
    margin:30,
	nav:true,
	autoplay:true,
	smartSpeed:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:3
        }
    }
})
$('#sanpham2').owlCarousel({
    loop:true,
    margin:30,
	nav:true,
	autoplay:true,
	smartSpeed:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:3
        }
    }
})


